name: Package Server

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/build.server.yml"
      - ".github/workflows/package.server.yml"

jobs:
  build:
    uses: ./.github/workflows/build.server.yml

  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true
          package_json_file: server/package.json

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build Docker Image
        run: docker build -t server:latest .

      - name: Save Docker Image
        run: docker save server:latest -o server-latest.tar

      - name: Upload Docker Image
        uses: actions/upload-artifact@v6
        with:
          name: docker-image-latest
          path: server-latest.tar
          if-no-files-found: error
